# fly.toml app configuration file generated for tevet-troc on 2025-03-14T04:51:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tevet-troc'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
