[build]
command = "pnpm run build"  # Use pnpm to run the build
publish = "dist"          # Adjust to your actual build output directory
functions = "dist/netlify/functions" # Adjust to your functions directory if different

[[redirects]]
from = "/*"
to = "/"
status = 200