export enum AmbulanceStatus {
  AVAILABLE = 'AVAILABLE',
  IN_SERVICE = 'IN_SERVICE',
  MAINTENANCE = 'MAINTENANCE',
  DISPATCHED = 'DISPATCHED',
  EN_ROUTE_TO_SCENE = 'EN_ROUTE_TO_SCENE', // More specific
  AT_SCENE = 'AT_SCENE',
  TRANSPORTING_PATIENT = 'TRANSPORTING_PATIENT',
  EN_ROUTE_TO_HOSPITAL = 'EN_ROUTE_TO_HOSPITAL',
  AT_HOSPITAL = 'AT_HOSPITAL', // Added
  RETURNING_TO_BASE = 'RETURNING_TO_BASE',
  UNAVAILABLE = 'UNAVAILABLE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE', // More specific
  ON_BREAK = 'ON_BREAK', // Added
  FUELING = 'FUELING', // Added
  CLEANING = 'CLEANING', // Added
  AWAITING_DISPATCH = 'AWAITING_DISPATCH', // Added
  PREPARING_FOR_MISSION = 'PREPARING_FOR_MISSION', // Added
  UNDER_REPAIR = 'UNDER_REPAIR', // More specific
}
