export enum AmbulanceType {
  BASIC_LIFE_SUPPORT = 'BASIC_LIFE_SUPPORT',
  ADVANCED_LIFE_SUPPORT = 'ADVANCED_LIFE_SUPPORT',
  MOBILE_INTENSIVE_CARE_UNIT = 'MOBILE_INTENSIVE_CARE_UNIT',
  PEDIATRIC_AMBULANCE = 'PEDIATRIC_AMBULANCE',
  NEONATAL_AMBULANCE = 'NEONATAL_AMBULANCE',
  RESCUE_AMBULANCE = 'RESCUE_AMBULANCE',
  BARIATRIC_AMBULANCE = 'BARIATRIC_AMBULANCE',
  WHEELCHAIR_VAN = 'WHEELCHAIR_VAN',
  AMBULATORY_TRANSPORT = 'AMBULATORY_TRANSPORT',
  PSYCHIATRIC_TRANSPORT = 'PSYCHIATRIC_TRANSPORT',
  LONG_DISTANCE_TRANSPORT = 'LONG_DISTANCE_TRANSPORT',
  AIR_AMBULANCE = 'AIR_AMBULANCE',
  WATER_AMBULANCE = 'WATER_AMBULANCE',
  HAZMAT_AMBULANCE = 'HAZMAT_AMBULANCE', // Hazardous materials
  EVENT_MEDICAL_SERVICES = 'EVENT_MEDICAL_SERVICES',
  CRITICAL_CARE_TRANSPORT = 'CRITICAL_CARE_TRANSPORT',
  RAPID_RESPONSE_VEHICLE = 'RAPID_RESPONSE_VEHICLE', // First responder type vehicle
  SUPERVISOR_VEHICLE = 'SUPERVISOR_VEHICLE', // For supervisors
  UTILITY_VEHICLE = 'UTILITY_VEHICLE', // For logistics/supplies
  COMMAND_VEHICLE = 'COMMAND_VEHICLE', // For incident command
  TRAINING_AMBULANCE = 'TRAINING_AMBULANCE',
}
