export enum EmergencyType {
  /** 🚗 Traffic & Transport */
  CAR_ACCIDENT = 'CAR_ACCIDENT',
  MOTORCYCLE_ACCIDENT = 'MOTORCYCLE_ACCIDENT',
  PEDESTRIAN_ACCIDENT = 'PEDESTRIAN_ACCIDENT',
  TRAIN_ACCIDENT = 'TRAIN_ACCIDENT',
  AIRPLANE_CRASH = 'AIRPLANE_CRASH',
  SHIP_ACCIDENT = 'SHIP_ACCIDENT',

  /** 🚑 Medical Emergencies */
  HEART_ATTACK = 'HEART_ATTACK',
  STROKE = 'STROKE',
  SEIZURE = 'SEIZURE',
  DIABETIC_EMERGENCY = 'DIABETIC_EMERGENCY',
  ALLERGIC_REACTION = 'ALLERGIC_REACTION',
  BREATHING_PROBLEM = 'BREATHING_PROBLEM',
  SEVERE_BURNS = 'SEVERE_BURNS',
  ELECTROCUTION = 'ELECTROCUTION',
  DROWNING = 'DROWNING',
  POISONING = 'POISONING',
  FALL_INJURY = 'FALL_INJURY',
  FRACTURE = 'FRACTURE',
  BLEEDING = 'BLEEDING',

  /** 🔥 Fires & Explosions */
  HOUSE_FIRE = 'HOUSE_FIRE',
  FOREST_FIRE = 'FOREST_FIRE',
  GAS_LEAK = 'GAS_LEAK',
  EXPLOSION = 'EXPLOSION',
  INDUSTRIAL_ACCIDENT = 'INDUSTRIAL_ACCIDENT',

  /** 🌪 Natural Disasters */
  EARTHQUAKE = 'EARTHQUAKE',
  FLOOD = 'FLOOD',
  TORNADO = 'TORNADO',
  HURRICANE = 'HURRICANE',
  LANDSLIDE = 'LANDSLIDE',
  TSUNAMI = 'TSUNAMI',

  /** 🚨 Crime & Violence */
  SHOOTING = 'SHOOTING',
  STABBING = 'STABBING',
  ROBBERY = 'ROBBERY',
  DOMESTIC_VIOLENCE = 'DOMESTIC_VIOLENCE',
  KIDNAPPING = 'KIDNAPPING',
  ASSAULT = 'ASSAULT',
  HOSTAGE_SITUATION = 'HOSTAGE_SITUATION',

  /** 🦠 Public Health */
  PANDEMIC = 'PANDEMIC',
  INFECTIOUS_DISEASE_OUTBREAK = 'INFECTIOUS_DISEASE_OUTBREAK',
  BIOLOGICAL_HAZARD = 'BIOLOGICAL_HAZARD',
  CHEMICAL_SPILL = 'CHEMICAL_SPILL',
  RADIATION_EXPOSURE = 'RADIATION_EXPOSURE',

  /** 🏗 Structural Failures */
  BUILDING_COLLAPSE = 'BUILDING_COLLAPSE',
  BRIDGE_COLLAPSE = 'BRIDGE_COLLAPSE',
  DAM_FAILURE = 'DAM_FAILURE',

  /** 🛠 Other */
  UNKNOWN = 'UNKNOWN',
  OTHER = 'OTHER',
}

export enum ReportedBy {
  USER ,
  COMPUTER ,
  OPERATOR ,
  AUTOMATED_SYSTEM ,
  THIRD_PARTY ,
}
