name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: corepack enable pnpm
      - run: echo "$PATH" # Debug: Check the PATH *after* corepack enable

      - name: Add pnpm to PATH
        run: echo "$HOME/.pnpm-store/v6/bin" >> $GITHUB_PATH  # Or find the correct path if different

      - run: echo "$PATH" # Debug: Check the PATH *after* adding pnpm

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build
